linters:
  disable-all: true
  enable:
    - govet
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bidichk
    - bodyclose
    - cyclop
    - decorder
    - depguard
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - exhaustruct
    - exportloopref
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - grouper
    - maintidx
    - nestif
    - nakedret
    - nilnil
    - nlreturn
    - nolintlint
    - paralleltest
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - testpackage
#    - tagliatelle
    - unconvert
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
run:
  go: 1.17
  skip-dirs:
    - apinto-build
    - scripts
    - frontend
  timeout: 10m
  issue-exit-code: 0
output:
#  format: checkstyle
  format: colored-line-number