# .goreleaser.yml
builds:
  - id: apinto
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    goarm:
      - "6"
    gomips:
      - hardfloat
    goamd64:
      - v1
    targets:
      - linux_amd64_v1
      - linux_arm64
      - linux_386
      - darwin_amd64_v1
      - darwin_arm64
    dir: ./app/apinto
    main: .
    binary: apinto
    builder: go
    gobinary: go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
archives:
  - id: default
    format: tar.gz
    wrap_in_directory: apinto
    files:
      - src: 'build/resources/*'
        dst: /
        strip_parent: true
release:
  github:
    owner: chen2eric
    name: apinto
  name_template: '{{.Tag}}'